services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Bot
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alembic
    env_file:
      - .env
    volumes:
      - .:/backend
    working_dir: /backend
    entrypoint: ["alembic", "-c", "alembic.ini", "upgrade", "head"]
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dv:/var/lib/postgresql/data


volumes:
  postgres_data_dv: