"""New migration

Revision ID: 6330ebdea626
Revises: 66b185aa936a
Create Date: 2025-05-30 13:46:28.968781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6330ebdea626'
down_revision: Union[str, None] = '66b185aa936a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'age')
    op.drop_table('media')
    # ### end Alembic commands ###
